### ISSUE TITLE
someone edited out the save buttons,

### ISSUE THREAD

**Issue by Adamus-prime616** [Redcrafter/lbr-save-editor#4]
someone edited out the Save buttons, also could use a table for shards, Electrical storage and cards, along with an ability to see max storage available for inventory.

I'm a machinst and know G code, but thats about it, sorry for the intrusive request

**Comment by Redcrafter** [comment]
This is the second time i hear about missing Save buttons. They're not missing though. They're just at the bottom of the page. Maybe i should move them.
Also I'm not really interested in the game anymore so i probably won't be adding features myself. But I'll accept Pull Requests from anyone who want's improve the editor.

**Comment by Redcrafter** [comment]
Fixed with 1ac5824
