### ISSUE TITLE
TypeError: str is undefined

### ISSUE THREAD

**Issue by Dregench** [Redcrafter/lbr-save-editor#8]
**Describe the bug**
Get a message saying "An Unexpected Error Occurred. Please open an issue on github.
TypeError: str is undefined"

**To Reproduce**
I'm afraid I don't know. I can't tell what changed to cause this.

**Expected behavior**
For the save file to load onto the page correctly.

**Save file**

[save.dat.zip](https://github.com/Redcrafter/lbr-save-editor/files/12839822/save.dat.zip)

**Additional context**

**Comment by Redcrafter** [comment]
Should be fixed now.
